language: android
jdk: oraclejdk7
# Use the Travis Container-Based Infrastructure
sudo: false

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

env:
  global:
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=21
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20 # minutes (2 minutes by default)

android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - tools # to install Android SDK tools 25.1.x
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$EMULATOR_API_LEVEL
    # For Google APIs
    - addon-google_apis-google-$ANDROID_API_LEVEL
    - addon-google_apis-google-$EMULATOR_API_LEVEL
    # Google Play Services
    - extra-google-google_play_services
    # Support library
    - extra-android-support
    # Latest artifacts in local repository
    - extra-google-m2repository
    - extra-android-m2repository
    # Specify at least one system image
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL

before_script:
  # Create and start emulator
  ##- mkdir -p "$ANDROID_HOME/licenses"
  ##- cp ./google-licenses/* "$ANDROID_HOME/licenses/"
  - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator

script:
  - ./gradlew clean check connectedCheck -x library:signArchives -PdisablePreDex

before_deploy:
- cp $TRAVIS_BUILD_DIR/example_keystore.jks $HOME
- cd app/build/outputs/apk/
- jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $HOME/example_keystore.jks -storepass $storepass -keypass $keypass app-release-unsigned.apk ExampleKeystoreAlias
# Verification
- jarsigner -verify app-release-unsigned.apk
- "${ANDROID_HOME}/build-tools/24.0.2/zipalign -v 4 app-release-unsigned.apk TakeHomeAPK.apk"

deploy:
  provider: releases
  file: TakeHomeAPK.apk
  skip_cleanup: true
  on:
    repo: take-home/maxi_takecoursequiz
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCZNi10cLA+B5aMjF3IZ3cDPEa4pcF08uVpkqrscsUADrt62YFnMoyBcH3Kv7Yf2L/7P6hUndbMJ3heh/yRdJ8npYE64AA1k4aBzD6MbivbtWJk8aK12ddEqSiFqVCc1oAb0MDfMk/fBFV43JijS6+UuZYqUfUzYyaNe+Obd91hrtjHxyYTeaWa7cG7Sg2KE8dKriSkKCxcPToDWovnbbU+5S7Z4dj0UiTcah+1VWNCkDyoGaocGjx9TxzEBo4LNn2TGTODp6+knuOaklllXZvuf6iozyRb7LROXMH//8DnmxRIs7I3C8strQH6dBQEXfB6QpoqyshTLhxYlfMSLaQ/ leonardmensah@Leonards-MBP-2.local.tld"